FROM node:22 AS web-builder

COPY web/package.json web/package-lock.json /web/
COPY web/shared/ /web/shared/
COPY web/frpc/ /web/frpc/
WORKDIR /web
RUN npm ci
WORKDIR /web/frpc
RUN npm run build

FROM golang:1.25 AS building

WORKDIR /building
COPY go.mod go.sum ./
RUN go mod download
COPY assets/ assets/
COPY client/ client/
COPY cmd/ cmd/
COPY pkg/ pkg/
COPY server/ server/
COPY web/frpc/embed.go web/frpc/embed.go
COPY --from=web-builder /web/frpc/dist /building/web/frpc/dist

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frpc -o bin/frpc ./cmd/frpc

FROM alpine:3

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frpc /usr/bin/frpc

ENTRYPOINT ["/usr/bin/frpc"]
